### PR TITLE
Prescription state management

### PR DESCRIPTION
**Pull request by smalho01**

### CODE REVIEW

**Comment by KeeyanGhoreshi** [comment]
I'm getting several typescript errors when trying to compile the frontend.  For example:

```
Property 'order' does not exist on type 'Object'.

44       if (response.order.dispenseStatus === "Approved") {
```

**Comment by smalho01** [comment]
> I'm getting several typescript errors when trying to compile the frontend. For example:
> 
> ```
> Property 'order' does not exist on type 'Object'.
> 
> 44       if (response.order.dispenseStatus === "Approved") {
> ```

huh, I thought this was working on my end. I'll investigate

**Comment by smalho01** [comment]
> I'm getting several typescript errors when trying to compile the frontend. For example:
> 
> ```
> Property 'order' does not exist on type 'Object'.
> 
> 44       if (response.order.dispenseStatus === "Approved") {
> ```

Fixed the typescript issue

**Review by KeeyanGhoreshi — APPROVED** [review]
LGTM

**Pull request merged**
